name: commit to pages # name key: property/value/function a basic workflow to publish commits to pages 
on: # on: Controls when the action will run. 
  push: # Triggers the workflow on push or pull request events but only for the master branch
   branches: [ master ] # push to master branch 
                            # pull_request:
                            # branches: [ master ]
                            
                            
  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2 # uses GitHub's checkout actions to checkout code from the master branch
      - name: Setup .Net Core SDK # Installs .Net core SDK 3.1
      - uses: actions/setup-dotnet@v1
        with:
         dotnet-version: 5.0.102
      - name: GitTools # version control utility
        uses: GitTools/actions@v0.9.9
        
# publishes SDK to the release folder      
      - name: Publish .NET Core Project # publishes Blazor project to the release-folder
        run: dotnet publish BlazorGitHubPagesDemo.csproj -c Release -o release --nologo
        
# Deploy the site           
      - name: GitHub Pages action # Deploys the site           
        uses: peaceiris/actions-gh-pages@v3.7.3

# resolves token use for communicating w/ GitHub up on your behalf.
        with: 
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         BRANCH: gh-pages
         FOLDER: release/wwwroot




      # Runs a single command using the runners shell
    #  - name: Run a one-line script
     #   run: echo Hello, world!

      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
        # run: |
         # echo Add other actions to build,
         # echo test, and deploy your project.
          
     #  - name: Publish .NET Core Project   # publishes Blazor project to the release-folder

      # run: dotnet publish BlazorGitHubPagesDemo.csproj -c Release -o release --nologo




